# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    # force all unspecified python hooks to run python3
    python: python3
repos:
-   repo: https://github.com/ambv/black
    rev: 18.9b0
    hooks:
    - id: black
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: flake8
        args: [--max-line-length=120, '--ignore=E203,W503']
    -   id: check-json
#    -   id: pretty-format-json
#        args: [--autofix, --no-sort-keys]
