language: python
python:
- '3.6'
install:
- pip install -U setuptools
- pip install .
- pip install -r requirements.txt
script:
- python setup.py test
- if [[ ${TRAVIS_PYTHON_VERSION:0:1} == "3" ]]; then pre-commit run --all-files; fi
- doit update_languages
after_success:
- git diff-index --quiet HEAD -- || .travis/push.sh
deploy:
  provider: pypi
  user: __token__
  password:
    secure: fwzGM3PUyZSWGcDnrWwo+GLh+kySJiBCNv4QWbM/l2dw2bpdRziDkbqq7zTtTmgxL4HGrd6TtJPq3QJS12JUtp0I8/lZFwMpjk5DkDDLeeIGoysGSIzw0VuI4/rsaRVlWf5BBPKcGouwf4BGSuXImJDn0pv62crrP2fG/Pnn3sWj5m6y+FPCdTB2LQGj1Jw7+lO/lWTXGS6QFc0siAgnLisrVZbOtZJXXv8vbqBNusfomKvxqAfNrYSwLSU52OF3Sk6YP2/JG7YOsMhdkUrEeAcxsWcy5xeDJ/lg773rrWnv2BPsHnZfzOagOY46B33uu02jalPiBRcvzUbWsuXwCBv8zZAJmeyIkf5/R+UDxGDgsnb1jBSFwPnYQDmUqHFpSbBMH87pN8V2aa9pl7yfDy/wx6tdWfpHkAVBfGWAF/MtKKsPjRoJNLYo+aEpd/BGGagDWm/PXDGPpPS2JF0sw4BrhD3w4WEhCiDHuW54vhLXjxx6TNX+0vwKcJA+VuhXq5lowbbUvwh5Yp4m9rWMM/AE/t8fxzukpwRQHuKvWQgbyOgs5X9TbrXspebYRU+4PgtrSwz8I6RiZDugf/ckP4xNjNoMf1DjXPhOUEsqC5H4jSAyJon2s+Mplmu1at91l7VZb1Zi+Cd6R+xwC1Y96k8a4taIKnKRP+4uBk3TS8c=
  distributions: sdist bdist_wheel
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^v[0-9]+.[0-9]+.[0-9]+$"
env:
  global:
    secure: bYXWpieVWLJctT3xo/2jNnsaiT7RM8C7VttYMZjCstxOr+8qL5jhCXkez/XqbYQ2WJmpW5C9AsK2MIwn1W9zrc9CSZ5VMONrwTqmT/tPmn4TvDTM4hLCVqMMz8wzq8kbfhdqCpTLCj8AqFlG/8emi9B2NN9wnWC/bS7hzSeBDOzl50s2soniyXIizq49BzAf9mOZ/+5MpbIxwt3v++ZfHkjYzamg+oxS3rrejWHi1drVUXhgIf72narfP7kLwfVm4jrfcfXbUm+Yf3MBQ0tO33jHlPhXRPFu1XdqDbYmEpMuQUtBasTrg2fuhraORxKpi7eFToIRg4K8DCN1Bj0ktPd83Voj2PnQBvyUqNHdIAfwER4ZAmBbDRmc7LDk58KqZFE5NB5HeL+/PFxwLRWIC4P+K0WWAWDy+y0rxzhXc8uNaghEBL03WvPKxv9OqGXdSL0vaPzVj5XnEZ7CHOxpCgG/kv5J4YtNCQycGo612IstRFMF0V07+HIpxrCX5F6C4FDt5zAFqnBRm2oB6cM9MV8foofed9z/h0q5qJ9N7btE5qnzqbnNdG/RMuS2EjOLwjz8IfXeRiToq0MC4LGDVISH4c/RUzU970OoIFvOyqi+J4bhUSNwFuB3dPPfGW2a/bg3CAZjM1XWpU6H1xhpBwkDSzNbCsRHRXhhtIGVUfY=
