language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -U setuptools
  - pip install .
  - pip install -r requirements.txt
# command to run tests
script:
  - python setup.py test
  - if [[ ${TRAVIS_PYTHON_VERSION:0:1} == "3" ]]; then pre-commit run --all-files; fi
