name: Compile Card DB

on: [pull_request, workflow_dispatch, push]

jobs:
  compile_card_db:
    runs-on: ubuntu-latest
    outputs:
      cardb_target: ${{ steps.filter.outputs.cardb_target }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: 3.9
      - run: |
          pip install -r requirements.txt
          pip install -r dev-requirements.txt
          pip install .
      - name: Update Languages
        run: doit update_languages
      - run: |
          pip install .
      - name: Install PyICU
        run: |
          sudo apt update
          sudo apt install python3-icu
      - name: test generation with compiled Languages
        run: pytest -k "test_languages"
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          base: HEAD
          filters: |
            cardb_target:
              - src/domdiv/card_db/**
      - name: Archive compiled card DB
        if: steps.filter.outputs.cardb_target == 'true'
        run: tar -czf compiled_card_db.tgz src/domdiv/card_db
      - name: Upload compiled card DB artifact
        uses: actions/upload-artifact@v6
        if: steps.filter.outputs.cardb_target == 'true'
        with:
          name: compiled-card-db
          path: compiled_card_db.tgz
  make_card_db_pr:
    needs: compile_card_db
    if: ${{ github.event.pull_request.number != null && needs.compile_card_db.outputs.cardb_target == 'true' }}
    uses: ./.github/workflows/make_card_db_pr.yml
    secrets: inherit
    with:
      source_pr_number: ${{ github.event.pull_request.number }}
      base_branch: ${{ github.event.repository.default_branch }}
      has_changes: true
