name: Lint and Test

on: [push, pull_request, workflow_dispatch]

jobs:
  lint_and_test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - uses: astral-sh/setup-uv@v6
      - run: |
          uv sync
      - name: Install PyICU
        if: ${{ matrix.os == 'ubuntu-latest'}}
        run: |
          sudo apt update
          sudo apt install python3-icu
      - name: Lint
        run: uv run pre-commit run --all-files --show-diff-on-failure -v
      - name: Test
        run: uv run pytest
